INSERT INTO empleados (nombre,apellido,email,telefono) VALUES ('Jose','Garcia','jg@gmail.com',2134542)
INSERT INTO empleados (nombre,apellido,email,telefono) VALUES ('Calrlos','Perez','cp@gmail.com',43542)
INSERT INTO empleados (nombre,apellido,email,telefono) VALUES ('Maria','Orue','mo@gmail.com',5123)
INSERT INTO empleados (nombre,apellido,email,telefono) VALUES ('Alec','Kiko','ar@gmail.com',893442)
INSERT INTO empleados (nombre,apellido,email,telefono) VALUES ('Alvaro','Moro','jfe@gmail.com',7382542)

INSERT INTO proyectos (nombre,fecha_inicio,fecha_fin,activo) VALUES ('Calrlos',"2022-02-11","2022-02-11",true)
INSERT INTO proyectos (nombre,fecha_inicio,fecha_fin,activo) VALUES ('Maria',"2022-02-11","2022-02-11",true)
INSERT INTO proyectos (nombre,fecha_inicio,fecha_fin,activo) VALUES ('Alec',"2022-02-11","2022-02-11",true)
INSERT INTO proyectos (nombre,fecha_inicio,fecha_fin,activo) VALUES ('Alvaro',"2022-02-11","2022-02-11",true)